#!/usr/bin/env python3
"""
fetch_ctftime.py — pull Hackchester's results from CTFtime into data/ctftime.json.

CTFtime's API has no CORS headers, so the browser can't call it; instead the
GitHub Action in .github/workflows/ctftime.yml runs this weekly and commits
the result. Run it by hand any time:

    python3 scripts/fetch_ctftime.py

Standard library only. Team id lives in data/site.json → ctftime.team_id.
"""
import html
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "data", "site.json")
OUT = os.path.join(ROOT, "data", "ctftime.json")
LOGO_DIR = os.path.join(ROOT, "assets", "img", "ctfs")
LOGO_MAX_BYTES = 600_000
UA = "Mozilla/5.0 (hackchester.net site builder; +https://github.com/Hackchester/website)"


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
        return data if binary else data.decode("utf-8")


def fetch_logo(event_url):
    """Download the event's logo into assets/img/ctfs/<id>.<ext> (once). Returns the site-relative path or None."""
    event_id = event_url.rstrip("/").split("/")[-1]
    os.makedirs(LOGO_DIR, exist_ok=True)
    for f in os.listdir(LOGO_DIR):
        if f.split(".")[0] == event_id:
            return f"assets/img/ctfs/{f}"
    try:
        info = json.loads(get(f"https://ctftime.org/api/v1/events/{event_id}/"))
        logo = info.get("logo") or ""
        if not logo:
            return None
        ext = os.path.splitext(logo.split("?")[0])[1].lower() or ".png"
        if ext not in (".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp"):
            return None
        blob = get(logo, binary=True)
        if len(blob) > LOGO_MAX_BYTES:
            print(f"  skipping logo for {event_id}: {len(blob)} bytes")
            return None
        with open(os.path.join(LOGO_DIR, event_id + ext), "wb") as f:
            f.write(blob)
        print(f"  saved logo for {event_id} ({len(blob)} bytes)")
        return f"assets/img/ctfs/{event_id}{ext}"
    except Exception as e:  # a missing logo must never break the fetch
        print(f"  logo for {event_id} failed: {e}")
        return None


def parse_events(page):
    """Return {year: [ {place, name, url, points, rating_points} ]} from the team page."""
    years = {}
    for pane in re.finditer(r'<div class="tab-pane[^"]*" id="rating_(\d{4})">(.*?)</table>', page, re.S):
        year, body = pane.group(1), pane.group(2)
        events = []
        for row in re.finditer(
            r'<td class="place">\s*(\d+)\s*</td>\s*<td><a href="(/event/\d+)">(.*?)</a></td>'
            r'\s*<td>([\d.]+)</td>\s*<td>([\d.]+)</td>', body):
            place, path, name, pts, rating = row.groups()
            events.append({
                "place": int(place),
                "name": html.unescape(name).strip(),
                "url": "https://ctftime.org" + path,
                "logo": fetch_logo("https://ctftime.org" + path),
                "points": float(pts),
                "rating_points": round(float(rating), 3),
            })
        years[year] = events
    return years


def main():
    site = json.load(open(SITE, encoding="utf-8"))
    team_id = site.get("ctftime", {}).get("team_id")
    if not team_id:
        sys.exit("data/site.json needs ctftime.team_id")

    api = json.loads(get(f"https://ctftime.org/api/v1/teams/{team_id}/"))
    page = get(f"https://ctftime.org/team/{team_id}")
    events = parse_events(page)

    years = {}
    for year, evs in events.items():
        r = api.get("rating", {}).get(year, {})
        years[year] = {
            "country_place": r.get("country_place"),
            "rating_place": r.get("rating_place"),
            "rating_points": round(r["rating_points"], 3) if r.get("rating_points") else None,
            "events": evs,
        }

    data = {
        "_comment": "GENERATED by scripts/fetch_ctftime.py — do not edit. Extra CTFs go in data/ctfs.json.",
        "fetched": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "team": api.get("name"),
        "team_id": team_id,
        "url": f"https://ctftime.org/team/{team_id}",
        "country": api.get("country"),
        "years": dict(sorted(years.items(), reverse=True)),
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    n = sum(len(y["events"]) for y in years.values())
    print(f"wrote data/ctftime.json — {n} events across {len(years)} year(s)")


if __name__ == "__main__":
    main()
